# 파란색으로 출력
echo "\033[34mRECOVERY SCRIPT RUN\033[0m"
echo "HEAT_FAIL_CODE: $HEAT_FAIL_CODE"
echo "HEAT_FAIL_TIME: $HEAT_FAIL_TIME"
echo "HEAT_FAIL_TIME_LAST: $HEAT_FAIL_TIME_LAST"
echo "HEAT_FAIL_INTERVAL: $HEAT_FAIL_INTERVAL"
echo "HEAT_FAIL_PID: $HEAT_FAIL_PID"
echo "HEAT_FAIL_CNT: $HEAT_FAIL_CNT"
sleep 20
echo "\033[34mRECOVERY SCRIPT DONE \033[0m"